---
title: "NS Covid Rates"
author: "Gordon Shotwell"
output: html_document
params:
  data: covid
---
```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(RcppRoll)
library(lubridate)
library(readr)
library(httr)
library(tidyr)
resp <- GET("https://api.covid19tracker.ca/reports/province/ns")
covid <- tibble(raw = content(resp)$data) %>% 
  unnest_auto(raw)

today <- covid %>% 
  filter(date == Sys.Date())

missed_dates <- c("2021-04-28", "2021-04-29", "2021-04-30")
makeup_date <- c("2021-05-02")

test_interp <- covid$change_tests[covid$date == makeup_date] / 4
covid$change_tests[covid$date %in% c(missed_dates, makeup_date)] <- test_interp

is_weekend <- wday(today(), label = TRUE) %in% c("Sun", "Sat")
manual <- NA
if (nrow(today) == 0 ||
    today$change_tests == 0 ||
    (today$change_vaccinations == 0 && !is_weekend)) {
  if (is.na(manual)) {
    stop("Data not yet reported")
  } else {
    if (!(as.character(Sys.Date()) %in% covid$date)) {
      covid <- bind_rows(covid, tibble(date = as.character(Sys.Date())))
    }
    lgl <- covid$date == as.character(Sys.Date())
    covid$change_tests[lgl] <- 10272
    covid$change_vaccinations <- 0
    covid$change_cases[lgl] <- manual
  }
}

covid <- covid %>% 
  mutate(active = total_cases - total_fatalities - total_recoveries,
         date = lubridate::ymd(date)) %>%
  filter(date > "2020-03-15") %>% 
  mutate(wave = dplyr::case_when(date < "2020-10-21" ~"Spring 2020", 
                                 date > "2021-04-01" ~ "Spring 2021", 
                                 TRUE ~ "Winter 2020")) %>% 
  mutate(wave = factor(wave, levels = c("Spring 2020", "Winter 2020", "Spring 2021"))) %>% 
  arrange(date) %>% 
  group_by(wave) %>% 
  mutate(date_num = as.numeric(date - min(date))) %>% 
  mutate(active = ifelse(active < 0, 0, active)) 

active_cases <- covid$active[nrow(covid)]
```

There are **`r active_cases`** active cases in Nova Scotia as of **`r max(covid$date[covid$change_tests > 0])`**.

The data comes from [the Covid Tracker API](https://api.covid19tracker.ca/). 

```{r plots, echo = FALSE, warning=FALSE, message=FALSE}
theme_set(theme_minimal())
```

# Cases 

```{r, echo = FALSE, warning=FALSE, message=FALSE}
covid %>% 
  ggplot(aes(x = date_num, y = active, group = wave, colour = wave)) +
  geom_step() +
  labs(y = "Active Cases",
       x = "Days since outbreak began",
       title = "Nova Scotia's third wave is worse than the first"
  ) +
  theme_light()

covid <- covid %>% 
  arrange(date) %>% 
  mutate(change_cases = ifelse(is.na(change_cases), 0, change_cases)) %>% 
  mutate(roll_cases = roll_mean(change_cases, 7, fill = NA, align = "right")) %>%
  mutate(eight_day = roll_sum(change_cases, 8, fill = NA, align = "right")) 

labs <- covid %>% 
  group_by(wave) %>% 
  summarise(max = max(roll_cases, na.rm = TRUE))

ggplot(covid, aes(x = date_num, y = roll_cases, group = wave, colour = wave)) +
  geom_line() +
  geom_point(aes(y = change_cases), alpha = 0.2) +
  scale_y_continuous(breaks = round(c(covid$roll_cases[nrow(covid)], labs$max), 1)) +
  labs(y = "New cases (7 day average)",
       x = "Days since outbreak began",
       title = "Nova Scotia's third wave is worse than the first") +
  theme(panel.grid.minor = element_blank())
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
covid %>%
  filter(change_tests > 0) %>% 
  mutate(roll_tests = roll_mean(change_tests, 7, fill = NA, align = "right")) %>%
  mutate(roll_positivity = roll_cases / roll_tests, 
         positivity = change_cases / change_tests) %>%
  filter(positivity < 0.2) %>% 
  ggplot(aes(x = date_num, y = roll_positivity,
             group = wave, colour  = wave)) +
  geom_line() +
  geom_point(aes(y = positivity), alpha = 0.2) +
  scale_y_continuous(label = scales::percent) +
  labs(y = "Test positivitiy (7 day average)",
       x = "Days since outbreak began",
       title = "The third wave's positivity is pretty low") 
```

# Hospitalizations 

```{r message=FALSE, warning=FALSE, echo=FALSE}

covid %>% 
  ggplot(aes(x = date_num, y = total_hospitalizations, colour = wave)) +
  theme_minimal() +
  geom_line() +
    labs(y = "Number of hospitalized patients",
       x = "Days since outbreak began",
       title = "More Nova Scotians are being hospitalized") 

covid %>% 
  mutate(lagged_hospital = total_hospitalizations / lag(active, 7)) %>% 
  filter(lag(active, 7) > 20) %>% 
  ggplot(aes(x = date_num, y = lagged_hospital, colour = wave)) +
  theme_minimal() +
  scale_y_continuous(labels = scales::percent) +
  geom_line() +
    labs(y = "Seven day lagged hospitalization rate",
       x = "Days since outbreak began",
       title = "More Nova Scotians are being hospitalized") 

```



# Vaccines

```{r message=FALSE, warning=FALSE, echo=FALSE}
vaccines <- covid %>% 
  arrange(desc(date)) %>% 
  select(date, change_vaccinations, change_vaccines_distributed, 
         total_vaccinations, total_vaccines_distributed, total_vaccinated, active) %>% 
  mutate(full_doses = 2 * total_vaccinated,
         reserved = total_vaccinations - full_doses,
         unused = total_vaccines_distributed - total_vaccinations - reserved)

vaccines <- vaccines %>% 
  filter(date > lubridate::ymd("2020-12-01")) %>% 
  mutate(date = lubridate::ymd(date)) %>% 
  mutate(in_freezer = total_vaccines_distributed - total_vaccinations) %>% 
  arrange(date)

plot_df <- vaccines %>% 
  mutate(vaccine_ratio = total_vaccinated / active) %>% 
  filter(!is.na(vaccine_ratio)) 

recent_vax <- vaccines %>% 
  filter(date == Sys.Date()) %>% 
  pull(change_vaccinations)
```


Nova Scotia administered **`r scales::comma(recent_vax)`** vaccine doses yesterday.

```{r message=FALSE, warning=FALSE, echo=FALSE}
can <- resp <- GET("https://api.covid19tracker.ca/reports/")
can <- tibble(raw = content(can)$data) %>% 
  unnest_auto(raw)

can <- can %>% 
  mutate(date = lubridate::ymd(date)) %>% 
  filter(date > "2021-01-01") %>% 
  mutate(Region = "Canada") %>% 
  mutate(vaccine_pace = roll_mean(change_vaccinations, 7, align = "right", fill = 0, na.rm = TRUE) / 37)


vax_comp <- vaccines %>% 
  arrange(date) %>% 
  mutate(Region = "Nova Scotia",
         vaccine_pace = roll_mean(change_vaccinations, 7, align = "right", fill = 0, na.rm = TRUE) / 0.975) %>% 
  bind_rows(can) %>% 
  filter(date > "2021-01-07") 

breaks <- vax_comp %>% 
  group_by(Region) %>% 
  arrange(desc(date)) %>% 
  slice(1) %>% 
  pull(vaccine_pace)

vax_comp %>% 
  ggplot(aes(x = date, y = vaccine_pace, group = Region, color = Region)) +
  geom_line() +
  labs(
    x = "Date",
    y = "Doses",
    title = "Nova Scotia Doses Administered",
    subtitle = "Seven-day average, per million residents"
  ) +
  scale_y_continuous(breaks = breaks, labels = scales::comma)

vaccines$date <- lubridate::ymd(vaccines$date)


get_immune <-  function(check_date, df = vaccines) {
  df %>% 
    ungroup() %>% 
    filter(date < check_date) %>% 
    select(change_vaccinations, date) %>% 
    arrange(desc(date)) %>% 
    mutate(immune_day = ifelse(row_number() > 13, 14, row_number()),
           immune_pct = 0.8 * immune_day / 14,
           immune_pop = change_vaccinations * immune_pct) %>% 
    pull(immune_pop) %>% 
    sum()
}

vaccines$immune <- purrr::map_dbl(vaccines$date, get_immune) / 1e6

ggplot(vaccines, aes(x = date, y = immune)) + 
  geom_line() +
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.8)) +
  labs (title = "Nova Scotia Aggregate immunity",
        subtitle = "Based on an expected 80% reduction in infection 14 days after first dose",
        y = "Aggregate immunity",
        x = "Date")


```

```{r message=FALSE, warning=FALSE, echo=FALSE}
provs <- GET("https://api.covid19tracker.ca/provinces")
provs <- tibble(raw = content(provs)) %>% 
  unnest_auto("raw")

provs <- provs %>% 
  mutate(code = tolower(code)) %>% 
  filter(population > 50000) 

get_province <- function(prov = "ns") {
  resp <- GET(paste0("https://api.covid19tracker.ca/reports/province/", prov), query = list(after = Sys.Date() - 6))
  covid <- tibble(raw = content(resp)$data) %>% 
    unnest_auto(raw)
  covid$prov <- prov
  return(covid)
}

dat <-  purrr::map_df(tolower(provs$code), get_province)

comp_df <- dat %>% 
  left_join(provs, by = c("prov" = "code")) %>% 
  mutate(date = lubridate::ymd(date)) %>% 
  group_by(prov, name) %>% 
  arrange(date) %>% 
  summarise(
    total_vaccines_distributed = mean(total_vaccines_distributed, na.rm = TRUE),
    total_vaccinations = mean(total_vaccinations, na.rm = TRUE),
    population = mean(population, na.rm = TRUE)
  ) %>% 
  mutate(population = population / 1e6) %>% 
  mutate(doses_stored_per_million = (total_vaccines_distributed - total_vaccinations) / population)

median_val <-  median(comp_df$doses_stored_per_million)

comp_df  %>% 
  ggplot(aes(y = forcats::fct_reorder(name, doses_stored_per_million), 
             x = doses_stored_per_million)) +
  geom_point() +
  scale_x_continuous(label = scales::comma) +
  labs(title = "Vaccine doses stored per capita",
       subtitle = "Seven day average",
       y = "Province",
       x = "Doses stored per million residents") + 
  theme_minimal()

```

```{r message=FALSE, warning=FALSE, echo=FALSE}
plot_df %>%
  ungroup() %>% 
  mutate(Reserved = reserved + total_vaccinations) %>% 
  select(date,  `Available` = total_vaccines_distributed, 
         `Administered` = total_vaccinations) %>% 
  pivot_longer(-date) %>% 
  mutate(name = factor(name, levels = c("Available", "Administered"))) %>% 
  filter(date > "2020-12-21") %>% 
  ggplot(aes(x = date, y = value, group = name, fill = name)) +
  geom_ribbon(aes(ymax = value, ymin = 0)) +
  labs(
    title = "Nova Scotia's vaccine distribution has been slow",
    x = "Date",
    y = "Doses",
    fill = "Doses"
  ) +
  scale_fill_viridis_d(option = "D") +
  scale_y_continuous(breaks = c(max(plot_df$total_vaccinations), 
                                max(plot_df$total_vaccines_distributed, na.rm = TRUE)),
                     labels = scales::comma) +
  theme(panel.grid.minor = element_blank())
```


```{r message=FALSE, warning=FALSE, echo=FALSE}
vaccines %>% 
  filter(date > "2020-12-15") %>% 
  ggplot(aes(x = date, y = in_freezer)) +
  geom_path() +
  scale_y_continuous(
    labels = scales::comma) +
  labs(title = "Nova Scotia has a lot of unused vaccine",
       y = "Stored doses",
       x = "Date") +
  theme(panel.grid.minor = element_blank()) 
```





